kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: rfern156-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: NDU1ZjNjZTdmZTM2MDkzOWRjNDc=
  secret: NGY4YTdjYjQ1OTNmODkzMDI1NWNmNDkzYWIyZjBlNGMyYzFhYmI1Zg==