
name: ds-image
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    name: Build and Push to Quay
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dsbase
    steps:
    - name: Checkout
      uses: 'actions/checkout@v3'

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASS }}

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push the image
      id: 'docker-push'
      run: |-
        docker tag $IMAGE_NAME:latest quay.io/rfern156/dsbase:latest
        docker tag $IMAGE_NAME:latest quay.io/rfern156/dsbase:$GITHUB_SHA
        docker push quay.io/rfern156/dsbase:
        docker push quay.io/rfern156/dsbase::$GITHUB_SHA